services:
  kafbat-kafka-ui:
    image: kafbat/kafka-ui:v1.5.0
    restart: unless-stopped
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - /opt/kafbat-kafka-ui/config:/etc/kafkaui
    networks:
      - kafbat-kafka-ui-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  kafbat-kafka-ui-network:
    driver: bridge
